name: Release

on:
  pull_request:
    branches:
      - main
      - 'beta*'
    types:
      - closed

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
